# Generated by Django 4.2.1 on 2023-05-31 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_homepage_email_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='title',
        ),
        migrations.AddField(
            model_name='homepage',
            name='concern',
            field=models.CharField(default='None', max_length=256),
            preserve_default=False,
        ),
    ]
