# Generated by Django 4.2.1 on 2023-05-31 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_remove_homepage_title_homepage_concern'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='email_address',
            new_name='email_id',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='concern',
            new_name='message_box',
        ),
        migrations.AddField(
            model_name='homepage',
            name='last_name',
            field=models.CharField(default='None', max_length=120),
            preserve_default=False,
        ),
    ]
