# Generated by Django 4.2.1 on 2023-06-03 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_rename_email_address_homepage_email_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailIds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_id', models.CharField(max_length=120)),
            ],
        ),
    ]
