# Generated by Django 4.2.1 on 2023-06-03 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_emailids'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HomePage',
            new_name='Messages',
        ),
    ]
